---
date: '2021-06-24'
sections:
  security_fixes:
    - Os pacotes foram atualizados para as últimas versões de segurança.
  bugs:
    - Um grande número de métricas `gauge-dependency-graph-api-dispatch_dispatch` poderiam acumular-se no Console de Gerenciamento.
    - O serviço sshd às vezes falharia em iniciar instâncias em execução na Google Cloud Platform.
    - Arquivos de atualização antigos continuariam no disco do usuário, gerando, às vezes, falta de espaço.
    - '`gh-migrator` exibiu um caminho incorreto para a saída do registro.'
    - Um arquivo de exportação falharia silenciosamente em importar pull requests se contivessem solicitações de revisão de equipes ausentes no arquivo.
  changes:
    - Atualize a versão do executor de {% data variables.product.prodname_actions %} no GHES 3.1 para [v2.278.0](https://github.com/actions/runner/releases/tag/v2.278.0)
  known_issues:
    - O registro npm de {% data variables.product.prodname_registry %} não retorna mais o valor de tempo em respostas de metadados. Isso foi feito para permitir melhorias substanciais de desempenho. Continuamos a ter todos os dados necessários para devolver um valor de tempo como parte da resposta aos metadados e retomaremos o retorno desse valor no futuro, assim que tivermos resolvido os problemas de desempenho existentes.
    - Em uma nova configuração de {% data variables.product.prodname_ghe_server %} sem qualquer usuário, um invasor pode criar o primeiro usuário administrador.
    - As regras de firewall personalizadas são removidas durante o processo de atualização.
    - Arquivos LFS do Git [enviados através da interface web](https://github.com/blog/2105-upload-files-to-your-repositories) são adicionados diretamente ao repositório e de forma incorreta.
    - Os problemas não podem ser fechados se contiverem um permalink para um blob no mesmo repositório, onde o caminho do arquivo blob's é maior que 255 caracteres.
    - Quando "Usuários podem pesquisar pelo GitHub.com" está habilitado com o GitHub Connect, os problemas em repositórios privados e internos não estão incluídos nos resultados de pesquisa do GitHub.com.
    - |
      Após a atualização de 3.0.x para 3.1.x, em alguns casos, o GitHub Actions pode falhar com um erro: `Um erro inesperado ocorreu ao executar este fluxo de trabalho. Para contornar esse problema, conecte ao shell administrativo (ssh) e execute:
      ```
      ghe-actions-console -s ações -c "Queue-ServiceJob -JobId 4DB1F4CF-19FD-40E0-A253-91288813DE8B"
      ```
    - Se o {% data variables.product.prodname_actions %} estiver habilitado para {% data variables.product.prodname_ghe_server %}, a desmontagem de um nó de réplica com `ghe-repl-teardown` será bem-sucedida, mas poderá retornar `ERROR:Running migrations`.
    - Os limites de recursos que são específicos para processamento de hooks pre-receive podem causar falha em alguns hooks pre-receive.
